apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-prime-example
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.0.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark_data/code/prime.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 2
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 20
  volumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-storage-pvc
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    volumeMounts:
      - name: spark-data
        mountPath: /opt/spark_data
    labels:
      version: 3.0.0
    serviceAccount: autodataspark-spark
  executor:
    cores: 1
    instances: 1
    memory: "1024m"
    volumeMounts:
      - name: spark-data
        mountPath: /opt/spark_data
    labels:
      version: 3.0.0